name: 📚 Documentation
description: Report a documentation issue or suggest improvements.
labels: ['documentation', 'enhancement', 'Issue: Documentation']
assignees:
  - DJBlackEagle

body:
  - type: markdown
    attributes:
      value: |
        # 📚 Documentation Issue
        Use this template to report missing, outdated, or unclear documentation. Provide as much detail as possible to help us improve it.

        Please fill out the sections below to help us address the issue effectively.

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # 📜 Terms

  - type: checkboxes
    id: existing_issue
    attributes:
      label: ⚠️ Is there an existing issue for this?
      description: Please search [here](./?q=is%3Aissue) to see if an issue already exists for this documentation topic.
      options:
        - label: I have searched the existing issues
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: ⚖️ Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/DJBlackEagle/testing-publish/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # 📋 Issue description

  - type: dropdown
    id: severity
    attributes:
      label: 🏷️ Severity Level
      description: How critical is this documentation issue?
      options:
        - 🚨 Critical - Misleading or missing essential documentation
        - ⚠️ High - Significant gaps or outdated information
        - ❕ Medium - Improvements needed for clarity or completeness
        - ✅ Low - Minor updates or cosmetic changes
      default: 2

  - type: textarea
    validations:
      required: true
    attributes:
      label: 📝 Describe the documentation issue
      description: 'Provide a clear and concise description of the problem. Include specific sections or pages where applicable.'
      placeholder: |
        The installation instructions are outdated because...

  - type: textarea
    validations:
      required: true
    attributes:
      label: ✍️ Suggested Improvement
      description: 'Provide a clear and concise description of what should be updated or improved.'
      placeholder: |
        The installation guide should include...

  - type: textarea
    attributes:
      label: 🔗 Relevant Links (Optional)
      description: 'Provide links to the affected documentation pages or related resources.'
      placeholder: |
        E.g., https://docs.example.com/setup-guide

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots
      description: Add screenshots
      placeholder: Drag and drop images here

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        ---

  - type: markdown
    attributes:
      value: Thanks for completing our form!
