name: ⚡ Suggestion for Improving Performance
description: Provide a suggestion to improve the performance.
labels:
  ['enhancement', 'performance', 'Issue: Suggestion for Improving Performance']
assignees:
  - DJBlackEagle
body:
  - type: markdown
    attributes:
      value: |
        # ⚡ Suggestion for Improving Performance issue
        Use this template to suggest how the application's performance can be enhanced. Provide as much detail as possible to help us understand and implement your idea.

        Please fill out the sections below to help us address the issue effectively.

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # 📜 Terms

  - type: checkboxes
    id: existing_issue
    attributes:
      label: ⚠️ Is there an existing issue for this?
      description: Please search [here](./?q=is%3Aissue) to see if an issue already exists for the bug you encountered
      options:
        - label: I have searched the existing issues
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: ⚖️ Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/DJBlackEagle/testing-publish/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # 📋 Issue description

  - type: dropdown
    id: severity
    attributes:
      label: 🏷️ Severity Level
      description: How critical is this issue?
      options:
        - 🚨 Critical - Severely impacts core functionality or usability
        - ⚠️ High - Noticeable impact on user experience
        - ❕ Medium - Performance is acceptable but can be optimized
        - ✅ Low - Minor or optional improvement
      default: 2

  - type: input
    id: package_version
    validations:
      required: true
    attributes:
      label: 🔢 Package version
      description: |
        Which version of are you using?
        **Tip**: Make sure that all of yours dependencies are in sync!
      placeholder: 2.1.1

  - type: textarea
    id: potential_impact
    attributes:
      label: 💥 Potential Impact
      description: Explain the potential benefits or outcomes if this improvement is implemented.
      placeholder: E.g., This change could reduce average page load time by 50%, improving user retention.

  - type: textarea
    validations:
      required: true
    attributes:
      label: ✍️ Describe the performance enhancement you are proposing and how we can try it out
      placeholder: |
        Cache `array.length` on the following lines ...

  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
    attributes:
      label: 🪜 Steps to Reproduce
      description: List the steps to reproduce the bug. Include as much detail as possible.
      placeholder: |
        1. `npm i`
        2. `npm start:dev`
        3. See error...
        4. Go to the login page
        5. Enter valid credentials
        6. Click on the login button
        7. Observe the error

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # 📦 Environment NodeJS

  - type: input
    id: node_version
    validations:
      required: true
    attributes:
      label: 🔢 Node.js version
      description: Which version of Node.js are you using?
      placeholder: 18.15.0

  - type: textarea
    id: dependencies
    validations:
      required: true
    attributes:
      label: 🧩 Dependencies of your project
      description: Your dependencies in your package.json
      placeholder: |
        "@inquirer/prompts": "^1.2.2",
        "class-transformer": "^0.5.1",
        "class-validator": "^0.14.0",
        "commander": "^10.0.1",
        "reflect-metadata": "^0.1.13"

  - type: textarea
    id: dev_dependencies
    validations:
      required: true
    attributes:
      label: 🔗 Dev dependencies of your project
      description: Your dev dependencies in your package.json
      placeholder: |
        "@types/node": "^20.1.7",
        "nodemon": "^2.0.22",
        "ts-node": "^10.9.1",
        "typescript": "^5.0.4"

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # 🛠️ Environment

  - type: dropdown
    id: os
    validations:
      required: true
    attributes:
      label: 💻 In which operating systems have you tested?
      multiple: false
      options:
        - Linux
        - macOS
        - Windows
      default: 0

  - type: input
    id: os_version
    validations:
      required: true
    attributes:
      label: 🔢 Which version of the operating system do you use?
      placeholder: Ubuntu 24.04.1 LTS

  - type: dropdown
    id: browsers
    attributes:
      label: 🌐 What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # ℹ️ Additional information

  - type: textarea
    validations:
      required: true
    attributes:
      label: 📊 Benchmarks result or another proof
      description: |
        If you've already prototyped a solution, share your results here
        If not, what makes you believe there will be a performance improvement?
      placeholder: |
        ```
        ```

        MacBook Pro Mid 2014, 2.5 GHz Quad-Core Intel Core i7, 16 GB 1600 MHz DDR3, SSD

  - type: dropdown
    id: ide
    attributes:
      label: 🖥️ IDE (Development Environment)
      description: Which IDE were you using?
      options:
        - 'Eclipse'
        - 'IntelliJ IDEA'
        - 'NetBeans'
        - 'Visual Studio Code'
        - 'Visual Studio'
        - 'WebStorm'
        - 'Other'
      default: 6

  - type: textarea
    id: additional_context
    attributes:
      label: ➕ Additional Context
      description: Provide any additional context, links, or resources to support your request.
      placeholder: E.g., Reference to similar features in other tools or mockups of the feature.

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        # 🌀 Other

  - type: textarea
    id: logs
    attributes:
      label: 📋 Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: markdown
    attributes:
      value: '&nbsp;'

  - type: markdown
    attributes:
      value: |
        ---

  - type: markdown
    attributes:
      value: Thanks for completing our form!
